version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres-db
    restart: always
    env_file:
      db.env
    volumes:
      - db_data_pod_demo:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db


volumes:
  db_data_pod_demo:
